name: deploy do github pages maria clara

on:
  push:
    branches:
      - main  

permissions:
  contents: read
  pages: write
  id-token: write

jobs:
  deploy:
    environment:
      name: github-pages-maria-clara
      url: ${{ steps.deployment.outputs.page_url }}
    runs-on: ubuntu-latest
    env:
      SUBPATH: "/teste-deploy-next"
    steps:
      # Clonar o repositório
      - name: Clonagem
        uses: actions/checkout@v4

      # Instalar dependências
      - name: Instalar dependências
        run: npm install

      # Build do projeto
      - name: Build do projeto
        run: npm run build

      # Configurar o GitHub Pages
      - name: Configurar GitHub Pages
        uses: actions/configure-pages@v5
        with:
          enablement: true

      # Enviar arquivos gerados pelo build
      - name: Enviar arquivos do projeto
        uses: actions/upload-pages-artifact@v3
        with:
          path: './dist' # ou o caminho correto da saída do build

      # Fazer deploy no GitHub Pages
      - name: Deploy Final
        uses: actions/deploy-pages@v4
        id: deployment
